### ISSUE TITLE
f2l_37: Uncaught No possible solution!

### ISSUE THREAD

**Issue by khoanguyen-3fc** [AshleyF/briefcubing#17]
Step to reproduce:

- Clear all selected algs
- Select f2l_37

and icon for this case isn't accurate

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16377833/164405762-19d74528-8200-4764-87e2-ba27d5be85ee.png">

**Comment by AshleyF** [comment]
Thanks for reporting! Fixed
