### ISSUE TITLE
Giiker cube ble data issue

### ISSUE THREAD

**Issue by caichunjian520** [AshleyF/briefcubing#5]
Seems Giiker encrypted their bluetooth data recently. So if someone purchased the latest cube, it won't work with bluetooth web apps on Github.

For example: 
In solved condition
the old ble data: 0x1234567833333333123456789abc000043414341

new ble data:
can be this: 0x843a3f4e743e77c8f4869801ab804bdbf617a782
or can be this: 0xda6d6a39fc105890d5def0a1494ba457756da7a7
or can be others

**Comment by AshleyF** [comment]
Thanks for reporting this!

Do you have any more info on the version of the cube you have? What it shows up as? i3s? When/where you got it?

I have the several versions which all seem to work.

**Comment by caichunjian520** [comment]
First time when I know it is from a new edition i3SE(special edition), but yesterday when I bought a new i3S cube, it still had the same issue.

I can buy the most recently cube because I am in China where the Giiker cube been made. I asked all Taobao sellers about it, they said only sold the new cube.

I think Giiker changed the Bluetooth data started from two months ago. So in other countries if Giiker cube been sold, the next in stock cubes will have the same issue as I said.

To confirm my thought, I bought a i3 cube to get it a try.

This kind of cube is totally different from old versions. When do not use for about 10 minutes(I may need to test and get a precious time), the cube will automatically power off to save battery.

The containing box cannot tell if the cube is new or not, the only way is to listen the sound when start charge or stop charge or connect or disconnect or power on. There is only one short “Di” in above conditions. (old version has different sound)

**Comment by AshleyF** [comment]
Humm... I have an i3S from November 2018 that I've used for testing. Perhaps I'll try getting a newer one (though can't seem to find i3SE for easy shipping to U.S.)

**Comment by AshleyF** [comment]
We just added support for the newer (encrypted) GiiKER. I don't actually have the newest 3x3, but have tested with the 2x2. I'm hoping that they are the same protocol at least.

If someone could try it out and report back here, that would be awesome!

**Comment by sonofhypnos** [comment]
It worked on my I3SE !!! 
This is an amazing web-app.
Thank you!

**Comment by AshleyF** [comment]
Wonderful!
