### ISSUE TITLE
ERROR (G): Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by bhg-batman-bhg** [AshleyF/briefcubing#6]
ERROR (G): Cannot read property 'endsWith' of undefined

is the error i get when trying to connect the gans 356 I that i recieved in the mail today.(100% charged)  works on the cube station app.  but willnot connect to this page.  have tryed it on phone and computer browsers.  get the same error.

**Comment by AshleyF** [comment]
The newest GAN 356i (released AUG 2019 at U.S. Nats) appears to be encrypted. Briefcubing does work with the version from the initial China release, JUN 2019. We're working on figuring it out... In the meantime, I did at least add detection of the newer version and put up a reasonable message. Will keep you posted...

**Comment by AshleyF** [comment]
This should be working now!
